version: '3'

volumes:
  help_to_heat_postgres_data: {}

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    image: help_to_heat_web
    depends_on:
      - help-to-heat-db
    env_file:
      - ./envs/web
    volumes:
      - ./:/app/:z
    ports:
      - "8012:8012"

  help-to-heat-db:
    image: postgres:13
    container_name: help_to_heat_postgres
    volumes:
      - help_to_heat_postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - ./envs/web
    expose:
      - "5432"
