# Generated by Django 3.2.19 on 2023-06-09 18:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frontdoor", "0005_feedback"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="answer",
            name="unique answer per page per session",
        ),
    ]
