export {}
context('Initial eligibility for all countries', () => {
  beforeEach(() => {
    cy.visit('http://localhost:3000/')
    cy.get('#content').should('be.visible')
  })

  it('should display "The scheme does not apply to homes in Northern Ireland', () => {
    cy.contains('Start').click()
    cy.get('form').should('be.visible')
    cy.get('[type="radio"][value="Northern Ireland"]').check()
    cy.contains('Continue').click()
    cy.get('h1').should(
      'contain',
      'The scheme does not apply to homes in Northern Ireland'
    )
  })
  it('should display "As your property is in Scotland, you must use a different service', () => {
    cy.contains('Start').click()
    cy.get('form').should('be.visible')
    cy.get('[type="radio"][value="Scotland"]').check()
    cy.contains('Continue').click()
    cy.get('h1').should(
      'contain',
      'As your property is in Scotland, you must use a different service'
    )
  })
  it('should display "Do you own your property?" when Wales is selected', () => {
    cy.contains('Start').click()
    cy.get('form').should('be.visible')
    cy.get('[type="radio"][value="Wales"]').check()
    cy.contains('Continue').click()
    cy.get('legend').should('contain', 'Do you own your property?')
  })

  it('should display "Do you own your own property?" when England is selected', () => {
    cy.contains('Start').click()
    cy.get('form').should('be.visible')
    cy.get('[type="radio"][value="England"]').check()
    cy.contains('Continue').click()
    cy.get('legend').should('contain', 'Do you own your property?')
  })
})

context('Shows path to suppliers for different users in Wales', () => {
  beforeEach(() => {
    cy.visit('http://localhost:3000/')
    cy.get('#content').should('be.visible')
  })
  it('shows the successful path to the supplier for a detached property in band H with no benefits', () => {
    cy.contains('Start now').click()
    cy.get('form').should('be.visible')
    cy.get('[type="radio"]').check('Wales')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('owner')
    cy.contains('Continue').click()
    cy.get('input[name="address.buildingNumberOrName"]').type('123')
    cy.get('input[name="address.postcode"]').type('CF24 4TE')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').first().check()
    cy.contains('Continue').click()
    cy.get('select').select('H')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()
    cy.get('select').select('D')
    cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
      .eq(0)
      .find('input')
      .type('15')

    cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
      .eq(1)
      .find('input')
      .type('12')

    cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
      .eq(2)
      .find('input')
      .type('2015')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('no')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('>£31k')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('house')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('detached')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('3+')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('solid')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('all')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()
    cy.get('td').should('contain', 'Wales')
    cy.contains('Continue').click()

    cy.get('h1').should('contain', 'You may be eligible for the following')
    cy.contains('Continue').click()

    cy.get('select').select('british-gas')
    cy.contains('Continue').click()
    cy.get('input[name="personalDetails.firstName"]').type('Barry')
    cy.get('input[name="personalDetails.lastName"]').type('Allen')
    cy.get('input[name="personalDetails.phoneNumber"]').type('07514852468')
    cy.get('input[name="personalDetails.email"]').type('barry.allen@starlabs.com')
    cy.contains('Continue').click()
    cy.contains('Continue').click()
    cy.get('div').should('contain', 'confirm_and_submit_error')
  })

  it('shows the successful path to the supplier for a tenant in semi-bungalow property in band B with benefits', () => {
    cy.contains('Start now').click()
    cy.get('form').should('be.visible')
    cy.get('[type="radio"]').check('Wales')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('tenant')
    cy.contains('Continue').click()
    cy.get('input[name="address.buildingNumberOrName"]').type('123')
    cy.get('input[name="address.postcode"]').type('CF24 4TE')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').first().check()
    cy.contains('Continue').click()
    cy.get('select').select('B')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()
    cy.get('select').select('E')
    cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
      .eq(0)
      .find('input')
      .type('15')

    cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
      .eq(1)
      .find('input')
      .type('12')

    cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
      .eq(2)
      .find('input')
      .type('2015')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('<£31k')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('bungalow')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('semi-detached')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('2')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('mix')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('some')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('no')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('unknown')
    cy.contains('Continue').click()
    cy.get('td').should('contain', 'Wales')
    cy.contains('Continue').click()
    cy.get('h1').should('contain', 'You may be eligible for the following')
    cy.contains('Continue').click()
    cy.get('select').select('bulb')
    cy.contains('Continue').click()
    cy.get('input[name="personalDetails.firstName"]').type('Barry')
    cy.get('input[name="personalDetails.lastName"]').type('Allen')
    cy.get('input[name="personalDetails.phoneNumber"]').type('07514852468')
    cy.get('input[name="personalDetails.email"]').type('barry.allen@starlabs.com')
    cy.contains('Continue').click()
    cy.contains('Continue').click()
    cy.get('div').should('contain', 'confirm_and_submit_error')
  })

  it('shows the successful path to the supplier for a social tentant flat in band H with no benefits', () => {
    cy.contains('Start now').click()
    cy.get('form').should('be.visible')
    cy.get('[type="radio"]').check('Wales')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('social-tenant')
    cy.contains('Continue').click()
    cy.get('input[name="address.buildingNumberOrName"]').type('123')
    cy.get('input[name="address.postcode"]').type('CF24 4TE')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').first().check()
    cy.contains('Continue').click()
    cy.get('select').select('C')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()
    cy.get('select').select('G')
    cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
      .eq(0)
      .find('input')
      .type('15')

    cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
      .eq(1)
      .find('input')
      .type('12')

    cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
      .eq(2)
      .find('input')
      .type('2015')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('<£31k')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('apartment')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('middle-floor')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('studio')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('cavity')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('none')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('no')
    cy.contains('Continue').click()
    cy.get('td').should('contain', 'Wales')
    cy.contains('Continue').click()

    cy.get('h1').should('contain', 'You may be eligible for the following')
    cy.contains('Continue').click()

    cy.get('select').select('shell')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()
    cy.get('input[name="personalDetails.firstName"]').type('Barry')
    cy.get('input[name="personalDetails.lastName"]').type('Allen')
    cy.get('input[name="personalDetails.phoneNumber"]').type('07514852468')
    cy.get('input[name="personalDetails.email"]').type('barry.allen@starlabs.com')
    cy.contains('Continue').click()
    cy.contains('Continue').click()
    cy.get('div').should('contain', 'confirm_and_submit_error')
  })

  it('shows the successful path to the supplier for a landlord in semi-bungalow property in band F with benefits', () => {
    cy.contains('Start now').click()
    cy.get('form').should('be.visible')
    cy.get('[type="radio"]').check('Wales')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('landlord')
    cy.contains('Continue').click()
    cy.get('input[name="address.buildingNumberOrName"]').type('123')
    cy.get('input[name="address.postcode"]').type('CF24 4TE')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').first().check()
    cy.contains('Continue').click()
    cy.get('select').select('F')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()
    cy.get('select').select('E')
    cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
      .eq(0)
      .find('input')
      .type('15')

    cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
      .eq(1)
      .find('input')
      .type('12')

    cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
      .eq(2)
      .find('input')
      .type('2015')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('>£31k')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('house')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('terraced')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('1')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('unknown')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('some')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()
    cy.get('td').should('contain', 'Wales')
    cy.contains('Continue').click()
    cy.get('h1').should('contain', 'You may be eligible for the following')
    cy.contains('Continue').click()
    cy.get('select').select('edf')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()
    cy.get('input[name="personalDetails.firstName"]').type('Barry')
    cy.get('input[name="personalDetails.lastName"]').type('Allen')
    cy.get('input[name="personalDetails.phoneNumber"]').type('07514852468')
    cy.get('input[name="personalDetails.email"]').type('barry.allen@starlabs.com')
    cy.contains('Continue').click()
    cy.contains('Continue').click()
    cy.get('div').should('contain', 'confirm_and_submit_error')
  })
})

context('Shows path to suppliers for different users in England', () => {
  beforeEach(() => {
    cy.visit('http://localhost:3000/')
    cy.get('#content').should('be.visible')
  })

  it('shows the successful path to the supplier for a detached property in band H with no benefits', () => {
    cy.get('button').should('contain', 'Start now')
    cy.contains('Start now').click()
    cy.get('form').should('be.visible')
    cy.get('[type="radio"]').check('England')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('owner')
    cy.contains('Continue').click()
    cy.get('input[name="address.buildingNumberOrName"]').type('16')
    cy.get('input[name="address.postcode"]').type('NW1 4AE')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').first().check()
    cy.contains('Continue').click()
    cy.get('select').select('H')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()
    cy.get('select').select('D')
    cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
      .eq(0)
      .find('input')
      .type('15')

    cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
      .eq(1)
      .find('input')
      .type('12')

    cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
      .eq(2)
      .find('input')
      .type('2015')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('no')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('>£31k')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('house')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('detached')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('3+')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('solid')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('all')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()
    cy.get('td').should('contain', 'England')
    cy.contains('Continue').click()

    cy.get('h1').should('contain', 'You may be eligible for the following')
    cy.contains('Continue').click()

    cy.get('select').select('british-gas')
    cy.contains('Continue').click()
    cy.get('input[name="personalDetails.firstName"]').type('Barry')
    cy.get('input[name="personalDetails.lastName"]').type('Allen')
    cy.get('input[name="personalDetails.phoneNumber"]').type('07514852468')
    cy.get('input[name="personalDetails.email"]').type('barry.allen@starlabs.com')
    cy.contains('Continue').click()
    cy.contains('Continue').click()
    cy.get('div').should('contain', 'confirm_and_submit_error')
  })

  it('shows the successful path to the supplier for a tenant in semi-bungalow property in band B with benefits', () => {
    cy.get('button').should('contain', 'Start now')
    cy.contains('Start now').click()
    cy.get('form').should('be.visible')
    cy.get('[type="radio"]').check('England')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('tenant')
    cy.contains('Continue').click()
    cy.get('input[name="address.buildingNumberOrName"]').type('16')
    cy.get('input[name="address.postcode"]').type('NW1 4AE')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').first().check()
    cy.contains('Continue').click()
    cy.get('select').select('B')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()

    cy.get('select').select('E')
    cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
      .eq(0)
      .find('input')
      .type('15')

    cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
      .eq(1)
      .find('input')
      .type('12')

    cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
      .eq(2)
      .find('input')
      .type('2015')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('<£31k')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('bungalow')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('semi-detached')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('2')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('mix')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('some')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('no')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('unknown')
    cy.contains('Continue').click()
    cy.get('td').should('contain', 'England')
    cy.contains('Continue').click()
    cy.get('h1').should('contain', 'You may be eligible for the following')
    cy.contains('Continue').click()
    cy.get('select').select('bulb')
    cy.contains('Continue').click()
    cy.get('input[name="personalDetails.firstName"]').type('Barry')
    cy.get('input[name="personalDetails.lastName"]').type('Allen')
    cy.get('input[name="personalDetails.phoneNumber"]').type('07514852468')
    cy.get('input[name="personalDetails.email"]').type('barry.allen@starlabs.com')
    cy.contains('Continue').click()
    cy.contains('Continue').click()
    cy.get('div').should('contain', 'confirm_and_submit_error')
  })

  it('shows the successful path to the supplier for a social tentant flat in band C with no benefits', () => {
    cy.get('button').should('contain', 'Start now')
    cy.contains('Start now').click()
    cy.get('form').should('be.visible')
    cy.get('[type="radio"]').check('England')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('social-tenant')
    cy.contains('Continue').click()
    cy.get('input[name="address.buildingNumberOrName"]').type('16')
    cy.get('input[name="address.postcode"]').type('NW1 4AE')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').first().check()
    cy.contains('Continue').click()
    cy.get('select').select('C')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()
    cy.get('select').select('G')
    cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
      .eq(0)
      .find('input')
      .type('15')

    cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
      .eq(1)
      .find('input')
      .type('12')

    cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
      .eq(2)
      .find('input')
      .type('2015')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('<£31k')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('apartment')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('middle-floor')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('studio')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('cavity')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('none')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('no')
    cy.contains('Continue').click()
    cy.get('td').should('contain', 'England')
    cy.contains('Continue').click()

    cy.get('h1').should('contain', 'You may be eligible for the following')
    cy.contains('Continue').click()

    cy.get('select').select('shell')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()
    cy.get('input[name="personalDetails.firstName"]').type('Barry')
    cy.get('input[name="personalDetails.lastName"]').type('Allen')
    cy.get('input[name="personalDetails.phoneNumber"]').type('07514852468')
    cy.get('input[name="personalDetails.email"]').type('barry.allen@starlabs.com')
    cy.contains('Continue').click()
    cy.contains('Continue').click()
    cy.get('div').should('contain', 'confirm_and_submit_error')
  })

  it('shows the successful path to the supplier for a landlord in semi-bungalow property in band F with benefits', () => {
    cy.get('button').should('contain', 'Start now')
    cy.contains('Start now').click()
    cy.get('form').should('be.visible')
    cy.get('[type="radio"]').check('England')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('landlord')
    cy.contains('Continue').click()
    cy.get('input[name="address.buildingNumberOrName"]').type('16')
    cy.get('input[name="address.postcode"]').type('NW1 4AE')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').first().check()
    cy.contains('Continue').click()
    cy.get('select').select('F')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()
    cy.get('select').select('E')
    cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
      .eq(0)
      .find('input')
      .type('15')

    cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
      .eq(1)
      .find('input')
      .type('12')

    cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
      .eq(2)
      .find('input')
      .type('2015')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('>£31k')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('house')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('terraced')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('1')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('unknown')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('some')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()
    cy.get('td').should('contain', 'England')
    cy.contains('Continue').click()
    cy.get('h1').should('contain', 'You may be eligible for the following')
    cy.contains('Continue').click()
    cy.get('select').select('edf')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()
    cy.get('input[name="personalDetails.firstName"]').type('Barry')
    cy.get('input[name="personalDetails.lastName"]').type('Allen')
    cy.get('input[name="personalDetails.phoneNumber"]').type('07514852468')
    cy.get('input[name="personalDetails.email"]').type('barry.allen@starlabs.com')
    cy.contains('Continue').click()
    cy.contains('Continue').click()
    cy.get('div').should('contain', 'confirm_and_submit_error')
  })
})

context('Shows unhappy path for different users in England', () => {
  beforeEach(() => {
    cy.visit('http://localhost:3000/')
    cy.get('#content').should('be.visible')
  })
  it('EPC expired in England', () => {
    cy.contains('Start now').click()
    cy.get('form').should('be.visible')
    cy.get('[type="radio"]').check('England')
    cy.contains('Continue').click()

    cy.get('[type="radio"]').check('owner')
    cy.contains('Continue').click()

    cy.get('input[name="address.buildingNumberOrName"]').type('16')
    cy.get('input[name="address.postcode"]').type('EN3 4TE')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').first().check()
    cy.contains('Continue').click()

    cy.get('select').select('F')
    cy.contains('Continue').click()

    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()

    cy.get('select').select('B')
    cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
      .eq(0)
      .find('input')
      .type('15')

    cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
      .eq(1)
      .find('input')
      .type('12')

    cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
      .eq(2)
      .find('input')
      .type('2001')
    cy.contains('Continue').click()

    cy.get('h1').should(
      'contain',
      'Your property does not meet the minimum EPC eligibility requirements.'
    )
  })

  it('EPC rating A in England', () => {
    cy.contains('Start now').click()
    cy.get('form').should('be.visible')
    cy.get('[type="radio"]').check('England')
    cy.contains('Continue').click()

    cy.get('[type="radio"]').check('owner')
    cy.contains('Continue').click()

    cy.get('input[name="address.buildingNumberOrName"]').type('16')
    cy.get('input[name="address.postcode"]').type('EN3 4TE')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').first().check()
    cy.contains('Continue').click()

    cy.get('select').select('D')
    cy.contains('Continue').click()

    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()

    cy.get('select').select('A')
    cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
      .eq(0)
      .find('input')
      .type('15')

    cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
      .eq(1)
      .find('input')
      .type('12')

    cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
      .eq(2)
      .find('input')
      .type('2020')
    cy.contains('Continue').click()

    cy.get('h1').should(
      'contain',
      'Your property does not meet the minimum EPC eligibility requirements.'
    )
  })

  it('Landlord with an expired EPC in England', () => {
    cy.contains('Start now').click()
    cy.get('form').should('be.visible')
    cy.get('[type="radio"]').check('England')
    cy.contains('Continue').click()

    cy.get('[type="radio"]').check('landlord')
    cy.contains('Continue').click()

    cy.get('input[name="address.buildingNumberOrName"]').type('16')
    cy.get('input[name="address.postcode"]').type('EN3 4TE')
    cy.contains('Continue').click()
    cy.get('[type="radio"]').first().check()
    cy.contains('Continue').click()

    cy.get('select').select('B')
    cy.contains('Continue').click()

    cy.get('[type="radio"]').check('yes')
    cy.contains('Continue').click()

    cy.get('select').select('C')
    cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
      .eq(0)
      .find('input')
      .type('15')

    cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
      .eq(1)
      .find('input')
      .type('12')

    cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
      .eq(2)
      .find('input')
      .type('2010')
    cy.contains('Continue').click()

    cy.get('h1').should(
      'contain',
      'Your property does not meet the minimum EPC eligibility requirements.'
    )
  })
  context('Shows unhappy path for different users in Wales', () => {
    beforeEach(() => {
      cy.visit('http://localhost:3000/')
      cy.get('#content').should('be.visible')
    })
    it('EPC expired in Wales', () => {
      cy.contains('Start now').click()
      cy.get('form').should('be.visible')
      cy.get('[type="radio"]').check('Wales')
      cy.contains('Continue').click()

      cy.get('[type="radio"]').check('owner')
      cy.contains('Continue').click()

      cy.get('input[name="address.buildingNumberOrName"]').type('16')
      cy.get('input[name="address.postcode"]').type('CF24 1QG')
      cy.contains('Continue').click()
      cy.get('[type="radio"]').first().check()
      cy.contains('Continue').click()

      cy.get('select').select('F')
      cy.contains('Continue').click()

      cy.get('[type="radio"]').check('yes')
      cy.contains('Continue').click()

      cy.get('select').select('B')
      cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
        .eq(0)
        .find('input')
        .type('15')

      cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
        .eq(1)
        .find('input')
        .type('12')

      cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
        .eq(2)
        .find('input')
        .type('2001')
      cy.contains('Continue').click()

      cy.get('h1').should(
        'contain',
        'Your property does not meet the minimum EPC eligibility requirements.'
      )
    })

    it('EPC rating A in Wales', () => {
      cy.contains('Start now').click()
      cy.get('form').should('be.visible')
      cy.get('[type="radio"]').check('Wales')
      cy.contains('Continue').click()

      cy.get('[type="radio"]').check('owner')
      cy.contains('Continue').click()

      cy.get('input[name="address.buildingNumberOrName"]').type('16')
      cy.get('input[name="address.postcode"]').type('CF24 1QG')
      cy.contains('Continue').click()
      cy.get('[type="radio"]').first().check()
      cy.contains('Continue').click()

      cy.get('select').select('D')
      cy.contains('Continue').click()

      cy.get('[type="radio"]').check('yes')
      cy.contains('Continue').click()

      cy.get('select').select('A')
      cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
        .eq(0)
        .find('input')
        .type('15')

      cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
        .eq(1)
        .find('input')
        .type('12')

      cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
        .eq(2)
        .find('input')
        .type('2020')
      cy.contains('Continue').click()

      cy.get('h1').should(
        'contain',
        'Your property does not meet the minimum EPC eligibility requirements.'
      )
    })

    it('Landlord with an expired EPC in Wales', () => {
      cy.contains('Start now').click()
      cy.get('form').should('be.visible')
      cy.get('[type="radio"]').check('Wales')
      cy.contains('Continue').click()

      cy.get('[type="radio"]').check('landlord')
      cy.contains('Continue').click()

      cy.get('input[name="address.buildingNumberOrName"]').type('16')
      cy.get('input[name="address.postcode"]').type('CF24 1QG')
      cy.contains('Continue').click()
      cy.get('[type="radio"]').first().check()
      cy.contains('Continue').click()

      cy.get('select').select('B')
      cy.contains('Continue').click()

      cy.get('[type="radio"]').check('yes')
      cy.contains('Continue').click()

      cy.get('select').select('C')
      cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
        .eq(0)
        .find('input')
        .type('15')

      cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
        .eq(1)
        .find('input')
        .type('12')

      cy.get('[data-cy="propertyEpcDetails.propertyEpcDate"] label')
        .eq(2)
        .find('input')
        .type('2010')
      cy.contains('Continue').click()

      cy.get('h1').should(
        'contain',
        'Your property does not meet the minimum EPC eligibility requirements.'
      )
    })
  })
})
