# Generated by Django 3.2.19 on 2023-05-30 10:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0004_alter_epcrating_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PasswordResetRequest",
        ),
    ]
