# Generated by Django 3.2.19 on 2023-05-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0005_delete_passwordresetrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_otp",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="totp_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
