# Generated by Django 3.2.19 on 2023-06-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0007_rename_is_supplier_admin_user_is_service_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SERVICE_MANAGER", "Service Manager"),
                    ("TEAM_LEADER", "Team Leader"),
                    ("TEAM_MEMBER", "Team Member"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
