# Generated by Django 3.2.19 on 2023-06-22 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0009_data_migrate_roles"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_service_manager",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_team_leader",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_team_member",
        ),
    ]
