# Generated by Django 3.2.18 on 2023-03-15 10:57

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecoplus", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EpcRating",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("uprn", models.CharField(max_length=12)),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                            ("H", "H"),
                        ],
                        max_length=32,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
