# Generated by Django 4.2 on 2023-04-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecoplus", "0011_passwordresetrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="invite_accepted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="invited_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_token_sent_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
