# Generated by Django 3.2.18 on 2023-05-11 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="is_abandoned",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="passwordresetrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="reset_requests", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
