# Generated by Django 3.2.18 on 2023-05-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0002_auto_20230511_0623"),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="session_id",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
