# Generated by Django 3.2.18 on 2023-03-21 12:55

import help_to_heat.portal.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0002_epcrating"),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="supplier",
            field=models.CharField(
                choices=[
                    ("BRITISH_GAS", "British Gas"),
                    ("BULB", "Bulb"),
                    ("E_ENERGY", "E Energy"),
                    ("ECOTRICITY", "Ecotricity"),
                    ("EDF", "EDF"),
                    ("EON", "EON"),
                    ("ESB", "ESB"),
                    ("FOXGLOVE", "Foxglove"),
                    ("OCTOPUS", "Octopus"),
                    ("OVO", "OVO"),
                    ("SCOTTISH_POWER", "Scottish Power"),
                    ("SHELL", "Shell"),
                    ("UTILITA", "Utilita"),
                    ("UTILITY_WAREHOUSE", "Utility Warehouse"),
                ],
                default=help_to_heat.portal.models.pick_random_supplier,
                max_length=64,
            ),
        ),
    ]
