# Generated by Django 3.2.18 on 2023-03-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0003_referral_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_supplier_user",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="supplier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BRITISH_GAS", "British Gas"),
                    ("BULB", "Bulb"),
                    ("E_ENERGY", "E Energy"),
                    ("ECOTRICITY", "Ecotricity"),
                    ("EDF", "EDF"),
                    ("EON", "EON"),
                    ("ESB", "ESB"),
                    ("FOXGLOVE", "Foxglove"),
                    ("OCTOPUS", "Octopus"),
                    ("OVO", "OVO"),
                    ("SCOTTISH_POWER", "Scottish Power"),
                    ("SHELL", "Shell"),
                    ("UTILITA", "Utilita"),
                    ("UTILITY_WAREHOUSE", "Utility Warehouse"),
                ],
                default=None,
                max_length=64,
                null=True,
            ),
        ),
    ]
