# Generated by Django 3.2.18 on 2023-03-23 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0005_auto_20230321_1508"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="referrals",
                to="portal.supplier",
            ),
        ),
    ]
