# Generated by Django 3.2.18 on 2023-03-23 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0006_alter_referral_supplier"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_supplier_user",
            new_name="is_supplier",
        ),
    ]
