# Generated by Django 3.2.19 on 2023-05-29 18:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frontdoor", "0002_auto_20230516_0929"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["created_at"]},
        ),
    ]
