name: Check code

env:
  DOCKER_BUILDKIT: 1

on:
  push:
    branches:
      - 'main'
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'develop'
      - 'suppliers'
      - 'sandbox'
      - 'staging'

jobs:
  check_web:
    name: Check code

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools
        pip install -r flake8 flake8-isort flake8-print flake8-blind-except pep8-naming black

    - name: Check code formatting
      run: |
        black --check .

    - name: Check code imports
        isort --check .

    - name: Check code linting
        flake8 .


  run_tests:
    name: Run tests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run tests
      run: |
        docker-compose -f tests/docker-compose.yml build tests-help-to-heat help-to-heat-test-db
        docker-compose -f tests/docker-compose.yml run --rm tests-help-to-heat


  check_migrations:
    name: Check migrations

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |
          docker-compose build web
          docker-compose run web python manage.py migrate
          docker-compose run web python manage.py makemigrations --check
